## to run this file, type command -> docker-compose -f jenkins.yml up/down/start/stop
version: '3'

networks:
  network:
    driver: bridge

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    ## "restart" will always start this service automatically when docker application starts and also it will restart the service if it fails.
    #restart: always
    ## it will restart the service if it fails.
    #restart: on-failure
    ports:
     - 80:8080
     - 443:8443
     - 50000:50000
    networks:
      - network
    volumes:
      - 'home:/var/jenkins_home'
      
volumes:
  home:
    driver: local