## to run this file, type command -> docker-compose -f mysql.yml up/down/start/stop
## if you get error as "ERROR: Invalid interpolation format for "environment" option in service "mysql", then escape the $ character in the password by writing extra $
version: '2'

networks:
  network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'syntel123$$'
    ports:
      - 3306:3306
    networks:
      - network
    volumes:
      - 'data:/mysql_data'

  mysql_client:
    image: adminer:4.7.6-standalone
    container_name: mysql_client
    ports:
      - 8002:8080
    networks:
      - network
      
volumes:
  data:
    driver: local