## to run this file, type command -> docker-compose -f postgres.yml up/down/start/stop
version: '2'

networks:
  network:
    driver: bridge
    
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - 'data:/postgres_data'

  postgres_client:
    image: adminer:4.7.6-standalone
    container_name: postgres_client
    ports:
      - 8001:8080
    networks:
      - network
      
volumes:
  data:
    driver: local